export const LOAD_GTFS_SUCCESS = 'LOAD_GTFS_SUCCESS';
export const SELECT_AGENCY = 'SELECT_AGENCY';
export const UPLOAD_CLICK = 'UPLOAD_CLICK';

export const POST_GTFS_SUCCESS = 'POST_GTFS_SUCCESS';
export const POST_GTFS_ERROR = 'POST_GTFS_ERROR';

export const PUBLISH_GTFS = 'PUBLISH_GTFS';
export const PUBLISH_GTFS_SUCCESS = 'PUBLISH_GTFS_SUCCESS';
export const PUBLISH_GTFS_ERROR = 'PUBLISH_GTFS_ERROR';

export const UNPUBLISH_GTFS = 'UNPUBLISH_GTFS';
export const UNPUBLISH_GTFS_SUCCESS = 'UNPUBLISH_GTFS_SUCCESS';
export const UNPUBLISH_GTFS_ERROR = 'UNPUBLISH_GTFS_ERROR';

export const VALIDATE_GTFS = 'VALIDATE_GTFS';
export const VALIDATE_GTFS_SUCCESS = 'VALIDATE_GTFS_SUCCESS';
export const VALIDATE_GTFS_ERROR = 'VALIDATE_GTFS_ERROR';

export const DELETE_GTFS = 'DELETE_GTFS';
export const DELETE_GTFS_SUCCESS = 'DELETE_GTFS_SUCCESS';
export const DELETE_GTFS_ERROR = 'DELETE_GTFS_ERROR';

export const HIDE_ALERT = 'HIDE_ALERT';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const TOKEN_SUCCESS = 'TOKEN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SET_USER_AGENCIES = 'SET_USER_AGENCIES';